variable "az1" {}
variable "az2" {}
variable "db_instance_type" {}
variable "db_pass" {}
variable "db_subnet_cidr_az1" {}
variable "db_subnet_cidr_az2" {}
variable "db_user" {}
variable "hostname" {}
variable "instance_type" {}
variable "region" {}
variable "subnet_cidr" {}
variable "tfe-pwd" {}
variable "tfe_release_sequence" {}
variable "vpc_cidr" {}
variable "unique_name" {}
variable "dns_zonename" {}
variable "certificate_email" {}
variable "dns_hostname" {}
